[package]
name = "qork"
version = "0.1.0"
authors = ["Philip Daniels <Philip.Daniels1971@gmail.com>"]

[dependencies]
slog-term = "2.0.2"
slog-async = "2.0.1"

# By default, in Release builds trace and debug are removed at compile time. and in debug builds,
# trace is removed. You can control that here using features.
[dependencies.slog]
version = "2.0.6"
# features = ["max_level_info"]
